name: Deploy ui1

on:
  push:
    branches: ["master", "staging"]
    paths:
      - "web/ui/**"
  workflow_dispatch:

concurrency:
  group: "ui1-pages"
  cancel-in-progress: false

env:
  VITE_DEVICE_ID: ${{ vars.DEVICE_ID }}
  VITE_IDENTITY_POOL_ID: ${{ vars.UI1_IDENTITY_POOL_ID }}
  VITE_MQTT_ENDPOINT: ${{ vars.MQTT_ENDPOINT }}
  VITE_REGION: ${{ vars.REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/ui/package-lock.json
      - name: Install ui1 dependencies
        run: npm ci
        working-directory: web/ui
      - name: Build ui1
        run: npm run build
        working-directory: web/ui
      - name: Upload ui1 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui1-dev
          path: web/ui/dist

  deploy:
    environment: cf-dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download ui1 artifact
        uses: actions/download-artifact@v4
        with:
          name: ui1-dev
          path: web/ui/dist
      - name: Deploy to CloudFlare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name irrigation-ui1-dev --branch ${{ github.ref_name }} web/ui/dist
