name: Deploy ui2

on:
  push:
    branches: ["master", "staging"]
  workflow_dispatch:

concurrency:
  group: "ui2-pages"
  cancel-in-progress: false

env:
  VITE_REGION: ${{ vars.REGION }}
  VITE_USER_POOL_ID: ${{ vars.USER_POOL_ID }}
  VITE_IDENTITY_POOL_ID: ${{ vars.IDENTITY_POOL_ID }}
  VITE_CLIENT_ID: ${{ vars.CLIENT_ID }}
  VITE_COGNITO_DOMAIN: ${{ vars.COGNITO_DOMAIN }}
  VITE_API_ENDPOINT: ${{ vars.API_ENDPOINT }}
  VITE_VAPID_PUB_KEY: ${{ vars.VAPID_PUB_KEY }}
  VITE_DEVICE_ID: ${{ vars.DEVICE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/ui2/package-lock.json
      - name: Install ui2 dependencies
        run: npm ci
        working-directory: web/ui2
      - name: Build ui2
        run: npm run build
        working-directory: web/ui2
      - name: Upload ui2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui2-dev
          path: web/ui2/dist

  deploy:
    environment: cf-dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download ui2 artifact
        uses: actions/download-artifact@v4
        with:
          name: ui2-dev
          path: web/ui2/dist
      - name: Deploy to CloudFlare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name irrigation-ui2-dev web/ui2/dist
